### ISSUE TITLE
accessing external image

### ISSUE THREAD

**Issue by plaszczy** [astrolabsoftware/spark-kernel-nersc#3]
woudl be nice to have the possibility to access other spark build images

**Comment by JulienPeloton** [comment]
Note for myself:
`create_shifter_kernel` --> `--image=nersc/spark-{}:v1` --> introduce args for the image to load.

**Comment by JulienPeloton** [comment]
Done in https://github.com/astrolabsoftware/spark-kernel-nersc/pull/4
